name: Check Module

on:
  workflow_call:
  push:
    branches: [ "master" ] 
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  check-module:
    uses: zero1limited/magento2-module-checks/.github/workflows/check_module.yml
    secrets: inherit