name: Check Description

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate composer.json and composer.lock
        run: composer validate --strict
      # - name: Install dependencies
      #   run: composer install --prefer-dist --no-progress
      - name: Foo
        run: |
          echo "yeah?"