name: Check Description

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [ "master" ] 
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  validate-composer-json:
    name: "Validate composer.json"
    runs-on: ubuntu-latest
    needs: [checkout]
    steps:
      - name: Check
        run: composer validate --strict
      # - name: Install dependencies
      #   run: composer install --prefer-dist --no-progress

  validate-description-composer-json:
    name: "Validate Description in composer.json"
    runs-on: ubuntu-latest
    needs: [checkout]
    steps:
      - name: Check
        run: |
          echo "yeah?"
          echo "======================"
          ls
          echo "======================"
          pwd
          echo "======================"
          php -r '$composerJson = json_decode(file_get_contents("composer.json"), true);  if(!array_key_exists("description", $composerJson) || strlen($composerJson["description"]) < 5){ echo "description in composer.json missing or too short".PHP_EOL;  exit(1); }else{ exit(0); }'
          echo "======================"

  all-valid:
    name: "All Valid"
    runs-on: ubuntu-latest
    needs: [validate-composer-json, validate-description-composer-json]
    steps:
      - name: Check
        run: |
          echo "yeah?"