name: Check Description

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [ "master" ] 
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  validate-composer-json:
    name: "Validate composer.json"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check
        run: composer validate --strict
      # - name: Install dependencies
      #   run: composer install --prefer-dist --no-progress

  validate-description-composer-json:
    name: "Validate Description in composer.json"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check
        run: |
          php -r '$composerJson = json_decode(file_get_contents("composer.json"), true);  if(!array_key_exists("description", $composerJson) || strlen($composerJson["description"]) < 5){ echo "description in composer.json missing or too short".PHP_EOL;  exit(1); }else{ exit(0); }'

  validate-magento-dependency-composer-json:
    name: "Validate magento/framework in composer.json"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check
        run: |
          echo "todo - check there is a dependency for magento/framework, check correct format"
          exit 1

  validate-php-dependency-composer-json:
    name: "Validate magento/framework in composer.json"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check
        run: |
          echo "todo - check there isn't a dependency for magento/framework"
          exit 1;

  phpstan:
    name: "PHP Stan"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check
        run: |
          echo "todo - phpstan"
          exit 1;

  phpcs:
    name: "PHP Coding Standards"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check
        run: |
          echo "todo - phpcs"
          exit 1;

  all-valid:
    name: "All Valid"
    runs-on: ubuntu-latest
    needs:
      - validate-composer-json
      - validate-description-composer-json
      - validate-magento-dependency-composer-json
      - phpstan
      - phpcs
    steps:
      - name: Check
        run: |
          echo "yeah?"