name: Check Description

on:
  workflow_dispatch:
  workflow_run:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Foo
        run: |
          echo "yeah?"